package POJO;
// Generated Aug 10, 2019 3:04:01 PM by Hibernate Tools 4.3.1



/**
 * DiemId generated by hbm2java
 */
public class DiemId  implements java.io.Serializable {


     private String maLop;
     private String maMh;
     private int mssv;

    public DiemId() {
    }

    public DiemId(String maLop, String maMh, int mssv) {
       this.maLop = maLop;
       this.maMh = maMh;
       this.mssv = mssv;
    }
   
    public String getMaLop() {
        return this.maLop;
    }
    
    public void setMaLop(String maLop) {
        this.maLop = maLop;
    }
    public String getMaMh() {
        return this.maMh;
    }
    
    public void setMaMh(String maMh) {
        this.maMh = maMh;
    }
    public int getMssv() {
        return this.mssv;
    }
    
    public void setMssv(int mssv) {
        this.mssv = mssv;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DiemId) ) return false;
		 DiemId castOther = ( DiemId ) other; 
         
		 return ( (this.getMaLop()==castOther.getMaLop()) || ( this.getMaLop()!=null && castOther.getMaLop()!=null && this.getMaLop().equals(castOther.getMaLop()) ) )
 && ( (this.getMaMh()==castOther.getMaMh()) || ( this.getMaMh()!=null && castOther.getMaMh()!=null && this.getMaMh().equals(castOther.getMaMh()) ) )
 && (this.getMssv()==castOther.getMssv());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMaLop() == null ? 0 : this.getMaLop().hashCode() );
         result = 37 * result + ( getMaMh() == null ? 0 : this.getMaMh().hashCode() );
         result = 37 * result + this.getMssv();
         return result;
   }   


}


