package POJO;
// Generated Aug 8, 2019 5:07:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Lop generated by hbm2java
 */
public class Lop  implements java.io.Serializable {


     private String maLop;
     private Set thoikhoabieus = new HashSet(0);
     private Set sinhviens = new HashSet(0);

    public Lop() {
    }

	
    public Lop(String maLop) {
        this.maLop = maLop;
    }
    public Lop(String maLop, Set thoikhoabieus, Set sinhviens) {
       this.maLop = maLop;
       this.thoikhoabieus = thoikhoabieus;
       this.sinhviens = sinhviens;
    }
   
    public String getMaLop() {
        return this.maLop;
    }
    
    public void setMaLop(String maLop) {
        this.maLop = maLop;
    }
    public Set getThoikhoabieus() {
        return this.thoikhoabieus;
    }
    
    public void setThoikhoabieus(Set thoikhoabieus) {
        this.thoikhoabieus = thoikhoabieus;
    }
    public Set getSinhviens() {
        return this.sinhviens;
    }
    
    public void setSinhviens(Set sinhviens) {
        this.sinhviens = sinhviens;
    }




}


