package POJO;
// Generated Aug 8, 2019 5:07:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Monhoc generated by hbm2java
 */
public class Monhoc  implements java.io.Serializable {


     private String maMh;
     private String tenMh;
     private Set thoikhoabieus = new HashSet(0);

    public Monhoc() {
    }

	
    public Monhoc(String maMh) {
        this.maMh = maMh;
    }
    public Monhoc(String maMh, String tenMh, Set thoikhoabieus) {
       this.maMh = maMh;
       this.tenMh = tenMh;
       this.thoikhoabieus = thoikhoabieus;
    }
   
    public String getMaMh() {
        return this.maMh;
    }
    
    public void setMaMh(String maMh) {
        this.maMh = maMh;
    }
    public String getTenMh() {
        return this.tenMh;
    }
    
    public void setTenMh(String tenMh) {
        this.tenMh = tenMh;
    }
    public Set getThoikhoabieus() {
        return this.thoikhoabieus;
    }
    
    public void setThoikhoabieus(Set thoikhoabieus) {
        this.thoikhoabieus = thoikhoabieus;
    }




}


