package POJO;
// Generated Aug 8, 2019 5:07:21 PM by Hibernate Tools 4.3.1



/**
 * Sinhvien generated by hbm2java
 */
public class Sinhvien  implements java.io.Serializable {


     private int mssv;
     private Lop lop;
     private String hoTen;
     private String gioiTinh;
     private Integer cmnd;

    public Sinhvien() {
    }

	
    public Sinhvien(int mssv) {
        this.mssv = mssv;
    }
    public Sinhvien(int mssv, Lop lop, String hoTen, String gioiTinh, Integer cmnd) {
       this.mssv = mssv;
       this.lop = lop;
       this.hoTen = hoTen;
       this.gioiTinh = gioiTinh;
       this.cmnd = cmnd;
    }
   
    public int getMssv() {
        return this.mssv;
    }
    
    public void setMssv(int mssv) {
        this.mssv = mssv;
    }
    public Lop getLop() {
        return this.lop;
    }
    
    public void setLop(Lop lop) {
        this.lop = lop;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public Integer getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(Integer cmnd) {
        this.cmnd = cmnd;
    }




}


