package POJO;
// Generated Aug 8, 2019 5:07:21 PM by Hibernate Tools 4.3.1



/**
 * Thoikhoabieu generated by hbm2java
 */
public class Thoikhoabieu  implements java.io.Serializable {


     private ThoikhoabieuId id;
     private Lop lop;
     private Monhoc monhoc;
     private String phongHoc;

    public Thoikhoabieu() {
    }

	
    public Thoikhoabieu(ThoikhoabieuId id, Lop lop, Monhoc monhoc) {
        this.id = id;
        this.lop = lop;
        this.monhoc = monhoc;
    }
    public Thoikhoabieu(ThoikhoabieuId id, Lop lop, Monhoc monhoc, String phongHoc) {
       this.id = id;
       this.lop = lop;
       this.monhoc = monhoc;
       this.phongHoc = phongHoc;
    }
   
    public ThoikhoabieuId getId() {
        return this.id;
    }
    
    public void setId(ThoikhoabieuId id) {
        this.id = id;
    }
    public Lop getLop() {
        return this.lop;
    }
    
    public void setLop(Lop lop) {
        this.lop = lop;
    }
    public Monhoc getMonhoc() {
        return this.monhoc;
    }
    
    public void setMonhoc(Monhoc monhoc) {
        this.monhoc = monhoc;
    }
    public String getPhongHoc() {
        return this.phongHoc;
    }
    
    public void setPhongHoc(String phongHoc) {
        this.phongHoc = phongHoc;
    }




}


