/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlysinhvien_02;

import DAO.PhucKhaoDAO;
import POJO.LichPhucKhao;
import POJO.PhucKhao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gogojungle
 */
public class DanhSachPhucKhao extends javax.swing.JFrame {

    /**
     * Creates new form DanhSachPhucKhao
     */
    QuanLyPhucKhao quanLiPhucKhao;
    private int idLichPhucKhao;
    final String[] columnNames = {
        "STT", "ID", "MSSV", "Họ Tên", "Môn Học", "Cột Điểm", "Điểm Đề Nghị", "Lý Do", "Trạng Thái"
    };
    
    
    public DanhSachPhucKhao() {
        initComponents();
    }

    public DanhSachPhucKhao(QuanLyPhucKhao qlpk, int idLich){
        this.quanLiPhucKhao = qlpk;
        this.idLichPhucKhao = idLich;
        this.quanLiPhucKhao.setVisible(false);
        initComponents();
        initLayout();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableListPhucKhao = new javax.swing.JTable();
        panelUpdate = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textMSSV = new javax.swing.JTextField();
        textHoTen = new javax.swing.JTextField();
        textMaMH = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaLyDo = new javax.swing.JTextArea();
        textDiemRequest = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboCotDiem = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboStatus = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lableNotify = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Danh Sách Phúc Khảo Sinh Viên");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableListPhucKhao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableListPhucKhao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableListPhucKhao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListPhucKhaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableListPhucKhao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 343, 895, 220));

        panelUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("MSSV: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Họ Tên:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Mã Môn:");

        textMSSV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textMSSV.setEnabled(false);

        textHoTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textHoTen.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Cột Điểm:");

        textAreaLyDo.setColumns(20);
        textAreaLyDo.setRows(5);
        jScrollPane2.setViewportView(textAreaLyDo);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Điểm Đề Nghị:");

        comboCotDiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GK", "CK", "Khac" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Lý Do:");

        jComboStatus.setEditable(true);
        jComboStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa Xem", "Đã Cập Nhật", "Không Cập Nhật" }));
        jComboStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboStatusActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Tình Trạng:");

        btnUpdate.setBackground(new java.awt.Color(153, 204, 255));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setText("Cập Nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUpdateLayout = new javax.swing.GroupLayout(panelUpdate);
        panelUpdate.setLayout(panelUpdateLayout);
        panelUpdateLayout.setHorizontalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUpdateLayout.createSequentialGroup()
                        .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUpdateLayout.createSequentialGroup()
                                .addComponent(textHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(panelUpdateLayout.createSequentialGroup()
                                .addComponent(textMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)))
                        .addGap(18, 18, 18))
                    .addGroup(panelUpdateLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)))
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDiemRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCotDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUpdateLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jComboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateLayout.createSequentialGroup()
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addContainerGap())
        );
        panelUpdateLayout.setVerticalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(comboCotDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(textDiemRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUpdateLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateLayout.createSequentialGroup()
                        .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33))))
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(panelUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 56, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Danh Sách Sinh Viên Phúc Khảo ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 313, -1, -1));

        lableNotify.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lableNotify.setForeground(new java.awt.Color(255, 51, 51));
        lableNotify.setText("Không Có Yêu Cầu Phúc Khảo...");
        getContentPane().add(lableNotify, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 313, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableListPhucKhaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListPhucKhaoMouseClicked
        // TODO add your handling code here:
        int select = tableListPhucKhao.getSelectedRow();
                
        if(select >= 0){
            panelUpdate.setVisible(true);
            
            String mssv = tableListPhucKhao.getValueAt(select, 2).toString();
            String hoTen = tableListPhucKhao.getValueAt(select, 3).toString();
            String maMon = tableListPhucKhao.getValueAt(select, 4).toString();
            String cotDiem = tableListPhucKhao.getValueAt(select, 5).toString();
            String diem = tableListPhucKhao.getValueAt(select, 6).toString();
            String lyDo = tableListPhucKhao.getValueAt(select, 7).toString();
            String status = tableListPhucKhao.getValueAt(select, 8).toString();
            
            textMSSV.setText(mssv);
            textHoTen.setText(hoTen);
            textMaMH.setText(maMon);
            comboCotDiem.setSelectedItem(cotDiem);
            textDiemRequest.setText(diem);
            textAreaLyDo.setText(lyDo);
            jComboStatus.setSelectedItem(status);
        } else {
            JOptionPane.showMessageDialog(null, "Vui Lòng Chọn Dòng Để Thực Hiện ...", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tableListPhucKhaoMouseClicked

    private void jComboStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboStatusActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int select = tableListPhucKhao.getSelectedRow();
        int status = jComboStatus.getSelectedIndex();
        tableListPhucKhao.getValueAt(select, 2).toString();
        
        String id = (String) tableListPhucKhao.getValueAt(select, 1);
        Integer idPhucKhao = Integer.parseInt(id);
        PhucKhao phucKhao = PhucKhaoDAO.getThongTin(idPhucKhao);
        
        if(phucKhao != null){
            phucKhao.setStatus(status);
            boolean result = PhucKhaoDAO.capNhatPhucKhao(phucKhao);
            System.out.println(result);
            if (result) {
                JOptionPane.showMessageDialog(null, "Cập Nhật Thành Công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);                
                this.panelUpdate.setVisible(false);
                initLayout();
            } else {
                JOptionPane.showMessageDialog(null, "Cập Nhật Thất Bại.", "Error", JOptionPane.INFORMATION_MESSAGE);
                initLayout();
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void initLayout(){
        lableNotify.setVisible(false);
        panelUpdate.setVisible(false);
        List<PhucKhao> list = PhucKhaoDAO.getListPhucKhao(idLichPhucKhao);
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columnNames);
        int stt = 1;
        if(list.size() > 0){
            for(PhucKhao i : list){
                // "STT", "ID", "MSSV", "Họ Tên", "Môn Học", "Cột Điểm", "Điểm Đề Nghị", "Lý Do", "Trạng Thái"
                String[] items = new String[9];
                items[0] = String.valueOf(stt);
                items[1] = i.getId().toString();
                items[2] = i.getMssv();
                items[3] = i.getHoTen();
                items[4] = i.getMaMh();
                items[5] = i.getCotDiem();
                items[6] = i.getDiemSuggest().toString();
                items[7] = i.getLyDo();
                if(i.getStatus() == 0){
                    items[8] = "Chưa Xem";
                } else if(i.getStatus() == 1){
                    items[8] = "Đã Cập Nhật";
                } else {
                    items[8] = "Không Cập Nhật";
                }
                
               model.addRow(items);
               stt++;
            }
            tableListPhucKhao.setModel(model);
        } else {
            lableNotify.setVisible(true);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhSachPhucKhao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhSachPhucKhao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhSachPhucKhao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhSachPhucKhao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DanhSachPhucKhao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboCotDiem;
    private javax.swing.JComboBox<String> jComboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lableNotify;
    private javax.swing.JPanel panelUpdate;
    private javax.swing.JTable tableListPhucKhao;
    private javax.swing.JTextArea textAreaLyDo;
    private javax.swing.JTextField textDiemRequest;
    private javax.swing.JTextField textHoTen;
    private javax.swing.JTextField textMSSV;
    private javax.swing.JTextField textMaMH;
    // End of variables declaration//GEN-END:variables
}
