/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlysinhvien_02;

import DAO.AccountDAO;
import DAO.DiemDAO;
import DAO.LopDAO;
import DAO.SinhVienDAO;
import DAO.SvMonHocDAO;
import DAO.ThoiKhoaBieuDAO;
import POJO.Account;
import POJO.Diem;
import POJO.Lop;
import POJO.Sinhvien;
import POJO.SvMonhoc;
import POJO.Thoikhoabieu;
import POJO.ThoikhoabieuId;
import java.time.LocalDate;
import java.util.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static quanlysinhvien_02.login.account;
/**
 *
 * @author Gogojungle
 */
public class infoSinhVien extends javax.swing.JFrame {

    /**
     * Creates new form infoSinhVien
     */
    
    private final String[] columnNamesScore = {
        "MSSV", "Họ Tên", "Điểm GK", "Điểm CK", "Điểm Khác", "Điểm Tổng", "Kết Quả"
    };    
    Sinhvien sv;
    login lg;
    Account acc;
    
    public infoSinhVien() { 
        initComponents();        
        initLayout();
    }

    public infoSinhVien(login _login, Account acount) {
        this.lg = _login;
        this.acc = acount;
        
        this.sv = SinhVienDAO.layThongTinSV(this.acc.getUsername());
        initComponents();
        this.lg.setVisible(false);
//        this.jPanelChangePasswd.setVisible(false);
        initLayout();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lableDiem = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnChangePass = new javax.swing.JButton();
        panelDoiMK = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textMKCu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textAgain = new javax.swing.JTextField();
        btnSaveNewPass = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        textMKMoi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCbBoxMonHoc = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        textMSSV = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDiemSV = new javax.swing.JTable();
        lableNotify = new javax.swing.JLabel();
        btnPhucKhao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thông Tin Sinh Viên");

        lableDiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lableDiem.setText("Bảng Điểm");

        btnLogout.setBackground(new java.awt.Color(204, 204, 204));
        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnChangePass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnChangePass.setText("Đổi MK");
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        panelDoiMK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Đổi Mật Khẩu");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Mật Khẩu Cũ:");

        textMKCu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nhập Lại MK:");

        textAgain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnSaveNewPass.setBackground(new java.awt.Color(0, 153, 153));
        btnSaveNewPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaveNewPass.setText("Lưu");
        btnSaveNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNewPassActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mật Khẩu Mới:");

        textMKMoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout panelDoiMKLayout = new javax.swing.GroupLayout(panelDoiMK);
        panelDoiMK.setLayout(panelDoiMKLayout);
        panelDoiMKLayout.setHorizontalGroup(
            panelDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDoiMKLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(panelDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textMKCu, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(textAgain))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDoiMKLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnSaveNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDoiMKLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(263, 263, 263))
        );
        panelDoiMKLayout.setVerticalGroup(
            panelDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDoiMKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(panelDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textMKCu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaveNewPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Môn Học:");

        jCbBoxMonHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCbBoxMonHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "item1" }));
        jCbBoxMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbBoxMonHocActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Sinh Viên:");

        textMSSV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textMSSV.setEnabled(false);
        textMSSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMSSVActionPerformed(evt);
            }
        });

        tableDiemSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableDiemSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDiemSVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDiemSV);

        lableNotify.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lableNotify.setForeground(new java.awt.Color(255, 51, 51));
        lableNotify.setText("jLabel1");

        btnPhucKhao.setBackground(new java.awt.Color(153, 204, 255));
        btnPhucKhao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPhucKhao.setText("Phúc Khảo");
        btnPhucKhao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhucKhaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jCbBoxMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panelDoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogout)
                            .addComponent(btnChangePass))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnPhucKhao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lableDiem)
                            .addGap(45, 45, 45)
                            .addComponent(lableNotify, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(158, 158, 158))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogout)
                        .addGap(18, 18, 18)
                        .addComponent(btnChangePass))
                    .addComponent(panelDoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jCbBoxMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(textMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableDiem)
                    .addComponent(lableNotify)
                    .addComponent(btnPhucKhao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void initLayout(){
        panelDoiMK.setVisible(false);
        lableNotify.setVisible(false);
        textMSSV.setText(this.acc.getUsername());
        btnPhucKhao.setVisible(false);
        addComboBox();
    }
    
    private void addTableScore(String _idSubject){
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(columnNamesScore);
        
        Diem diem = DiemDAO.diemSV(sv.getLop().getMaLop(), _idSubject, sv);
       
        if(diem != null){
//            System.out.println("diem: " + diem.getSv().getMssv() + diem.getMaMh() + diem.getDiemTong());
            String[] item = new String[7];
            item[0] = diem.getSv().getMssv();
            item[1] = diem.getSv().getHoTen();
            item[2] = String.valueOf(diem.getDiemGk());
            item[3] = String.valueOf(diem.getDiemCk());
            item[4] = String.valueOf(diem.getDiemKhac());
            item[5] = String.valueOf(diem.getDiemTong());
            item[6] = diem.xepLoai();
            
            tableModel.addRow(item);
        } 
        else {
            lableNotify.setVisible(true);
            lableNotify.setText("Chưa Cập Nhật Điểm !!!");
//            JOptionPane.showMessageDialog(null, "Chưa Cập Nhật Điểm !!!");
        }
        tableDiemSV.setModel(tableModel);         
    }
    
    private void addComboBox(){
        DefaultComboBoxModel cbModel = new DefaultComboBoxModel();   
        
        List<Thoikhoabieu> list = ThoiKhoaBieuDAO.layTKBByLop(sv.getLop().getMaLop());
        if(list.size() > 0){            
            for(Thoikhoabieu tkb : list){
//                System.out.println(tkb.getId().getMaMh() + " - " + tkb.getId().getMaLop());
                cbModel.addElement(tkb.getId().getMaMh() + " - " + tkb.getTenMon());
            }
            jCbBoxMonHoc.setModel(cbModel);
        }
        
    }
    
    private boolean validFormChangePass(){
        boolean valid = false;
        String oldPass = textMKCu.getText();
        String newPass = textMKMoi.getText();
        String passAgain = textAgain.getText();
        
        if(oldPass.equals("") || newPass.equals("") || passAgain.equals("")){
            JOptionPane.showMessageDialog(null, "Vui Lòng Nhập Mật Khẩu Đầy Đủ !!!", "Error", JOptionPane.ERROR_MESSAGE);
            valid = true;
        } else {
            if(!account.getPasswword().equals(oldPass)){
                JOptionPane.showMessageDialog(null, "Mật Khẩu Cũ Không Chính Xác!!!", "Error", JOptionPane.ERROR_MESSAGE);
                valid = true;
            } else if(!passAgain.equals(newPass)){
                JOptionPane.showMessageDialog(null, "Mật Khẩu Xác Nhận Không Chính Xác!!!", "Error", JOptionPane.ERROR_MESSAGE);
                valid = true;
            } else{
                valid = false;
            }                                 
        }
        return valid;
    }
    
    private void btnSaveNewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNewPassActionPerformed
        // TODO add your handling code here:
        boolean checked = validFormChangePass();
        if(!checked){
            String username = account.getUsername();
            Account acc = AccountDAO.layThongTinTaiKhoan(username);
            if(acc != null){
                acc.setPasswword(textMKMoi.getText());
                boolean kq = AccountDAO.updatePassword(acc);
                if(kq == true){
                   JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công.", "Notify", JOptionPane.INFORMATION_MESSAGE);
                    new login().setVisible(true);                    
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Đổi mật khẩu thất bại.", "Notify", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnSaveNewPassActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        // TODO add your handling code here:
        panelDoiMK.setVisible(true);
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void textMSSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMSSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMSSVActionPerformed

    private void jCbBoxMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbBoxMonHocActionPerformed
        // TODO add your handling code here:
        String value = jCbBoxMonHoc.getSelectedItem().toString();
        if(!value.equals("")){
            lableDiem.setText("Điểm Môn: " + value);
                        
            String[] words=value.split("\\s");
            
            addTableScore(words[0]);
            
        } else{
            JOptionPane.showMessageDialog(null, "Môn Học Chưa Cập Nhật!!!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jCbBoxMonHocActionPerformed

    private void tableDiemSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDiemSVMouseClicked
        // TODO add your handling code here:
        btnPhucKhao.setVisible(true);
    }//GEN-LAST:event_tableDiemSVMouseClicked

    private void btnPhucKhaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhucKhaoActionPerformed
        // TODO add your handling code here:
        // so sánh ngày hiện tại với ngày mở phúc khảo
//        LocalDate current = LocalDate.now();
        int index = tableDiemSV.getSelectedRow();
        TableModel md = tableDiemSV.getModel();
        
        String mssv = md.getValueAt(index, 0).toString();
        String hoTen = md.getValueAt(index, 1).toString();
        String monHoc = jCbBoxMonHoc.getSelectedItem().toString();
        
        FormTaoPhucKhao form = new FormTaoPhucKhao(mssv, hoTen, monHoc);
        form.setVisible(true);
    }//GEN-LAST:event_btnPhucKhaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(infoSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(infoSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(infoSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(infoSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new infoSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPhucKhao;
    private javax.swing.JButton btnSaveNewPass;
    private javax.swing.JComboBox<String> jCbBoxMonHoc;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lableDiem;
    private javax.swing.JLabel lableNotify;
    private javax.swing.JPanel panelDoiMK;
    private javax.swing.JTable tableDiemSV;
    private javax.swing.JTextField textAgain;
    private javax.swing.JTextField textMKCu;
    private javax.swing.JTextField textMKMoi;
    public javax.swing.JTextField textMSSV;
    // End of variables declaration//GEN-END:variables
}
