/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlysinhvien_02;

import DAO.MonHocDAO;
import DAO.ThoiKhoaBieuDAO;
import POJO.Monhoc;
import POJO.Thoikhoabieu;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gogojungle
 */
public class quanLyThoiKhoaBieu extends javax.swing.JFrame {

    /**
     * Creates new form quanLyThoiKhoaBieu
     */
    private String className = "";
    private String[] columnNames = {
        "STT", "Mã môn", "Tên môn", "Phòng học"
    };
    quanlylop qlLop;
    
    public quanLyThoiKhoaBieu() {
        initComponents();
        initLayout();
    }

    public quanLyThoiKhoaBieu(String _className, quanlylop _qlLop) {
        this.className = _className;
        this.qlLop = _qlLop;
        initComponents();
        initLayout();
        this.qlLop.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lableTKB = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTKB = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        notify = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Giáo Vụ Quản Lý");

        lableTKB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lableTKB.setForeground(new java.awt.Color(0, 153, 153));
        lableTKB.setText("TKB");

        tableTKB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTKB.setEnabled(false);
        jScrollPane1.setViewportView(tableTKB);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        notify.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        notify.setForeground(new java.awt.Color(255, 51, 0));
        notify.setText("Chưa Có Thời Khóa Biểu!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(lableTKB)
                                .addGap(33, 33, 33)
                                .addComponent(notify, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 59, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 377, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableTKB)
                    .addComponent(notify))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
       this.qlLop.setVisible(true);
       this.dispose();     
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanLyThoiKhoaBieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanLyThoiKhoaBieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanLyThoiKhoaBieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanLyThoiKhoaBieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quanLyThoiKhoaBieu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lableTKB;
    private javax.swing.JLabel notify;
    private javax.swing.JTable tableTKB;
    // End of variables declaration//GEN-END:variables

    private void initLayout() {
        List<Thoikhoabieu> list = ThoiKhoaBieuDAO.layDSTKB();
        showTKBOnTable();
    }
    
    private void showTKBOnTable(){
        notify.setVisible(false);
        DefaultTableModel table = new DefaultTableModel();
        table.setColumnIdentifiers(columnNames);
        lableTKB.setText("Thời Khóa Biểu " + className);
        List<Thoikhoabieu> tkb_lop = ThoiKhoaBieuDAO.layTKBByLop(className.replaceAll("\\?", ""));
        if(tkb_lop.size() > 0){
            int stt = 1;
            for(Thoikhoabieu i : tkb_lop){                
                Monhoc monHoc = MonHocDAO.laỵThongTinMonHoc(i.getId().getMaMh());
                
                String[] item = new String[4];
                item[0] = String.valueOf(stt);
                item[1] = i.getId().getMaMh();
                item[2] = monHoc.getTenMh();
                item[3] = i.getPhongHoc();
                
                table.addRow(item);
                stt++;
            }
            tableTKB.setModel(table);
        } else {
            notify.setVisible(true);
            tableTKB.setModel(table);
        }
    }
}
